{
  "openapi": "3.0.1",
  "info": { },
  "paths": {
    "/api/v1/notification/send": {
      "post": {
        "tags": [
          "FonePay"
        ],
        "requestBody": {
          "content": { }
        },
        "responses": {
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FonePayErrorModel"
                },
                "example": {
                  "timestamp": "24/11/2024 10:30:29 AM",
                  "status": 403,
                  "error": "Forbidden",
                  "message": "Invalid authorization data",
                  "path": null
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FonePayErrorModel"
                },
                "example": {
                  "timestamp": "24/11/2024 10:30:29 AM",
                  "status": 404,
                  "error": "Not Found !",
                  "message": "API Not Found",
                  "path": null
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FonePayErrorModel"
                },
                "example": {
                  "timestamp": "24/11/2024 10:30:29 AM",
                  "status": 400,
                  "error": "Bad Request",
                  "message": "Validation Error",
                  "path": null
                }
              }
            }
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FonePayErrorModel"
                },
                "example": {
                  "timestamp": "24/11/2024 4:45:29 AM",
                  "status": 502,
                  "error": "Bad Gateway",
                  "message": "Connection Timeout",
                  "path": null
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FonePayErrorModel"
                },
                "example": {
                  "timestamp": "24/11/2024 10:30:29 AM",
                  "status": 500,
                  "error": "Internal Error",
                  "message": "Contact With Error",
                  "path": null
                }
              }
            }
          },
          "429": {
            "description": "Too Many Requests",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FonePayErrorModel"
                },
                "example": {
                  "timestamp": "24/11/2024 4:45:29 AM",
                  "status": 429,
                  "error": "Too Many Request",
                  "message": "Rate Limit Exeeced",
                  "path": null
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "FonePayErrorModel": { },
      "FonePayNotificationRequestModel": { },
      "FonePayNotificationRequestProp": { }
    }
  }
}